config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :edit, :update, :show]
  root "groups#index"
  resources :groups do
    resources :comments, only: [:create, :destroy]
    resources :user_group_relations, only: [:create, :destroy]
  end
  resources :tags, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :tag_group_relation, dependent: :destroy
  has_many :tags, through: :tag_group_relation
  has_many :comments, dependent: :destroy
  has_many :user_group_relations, dependent: :destroy
  has_many :users, through: :user_group_relations


  # with_options presence: true do
  #   validates :title
  #   validates :details
  #   validates :start_date
  #   validates :end_date
  #   validates :deadline_date
  #   validates :max_num_of_people
  # end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_group_relation, dependent: :destroy
  has_many :group, through: :tag_group_relation

  validates :name, presence: true, uniqueness: true
end

app/models/tag_group.rb
class TagGroup
  include ActiveModel::Model
  attr_accessor :tag_ids, :user_id, :title, :details, :start_date, :end_date, :deadline_date, :max_num_of_people

  with_options presence: true do
    validates :user_id
    validates :title
    validates :details
    validates :start_date
    validates :end_date
    validates :deadline_date
    validates :max_num_of_people
  end

  def save
    group = Group.create(title: title, details: details, start_date: start_date, end_date: end_date, deadline_date: deadline_date, max_num_of_people: max_num_of_people, user_id: user_id)
    UserGroupRelation.create(user_id: user_id, group_id: group.id)
    tag_ids.each do |id|
      if id != ""
        TagGroupRelation.create(tag_id: id, group_id: group.id)
      end
    end
  end

end

app/models/tag_group_relation.rb
class TagGroupRelation < ApplicationRecord
  belongs_to :group
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :comments
  has_many :user_group_relations
  has_many :groups, through: :user_group_relations

  
  validates :nickname, presence: true
end

app/models/user_group_relation.rb
class UserGroupRelation < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def move_to_login_page
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :move_to_login_page
  before_action :move_to_show, only: [:destroy]

  def create
    comment = Comment.new(comment_params)
    if comment.valid?
      comment.save
    end
    redirect_to group_path(params[:group_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to group_path(params[:group_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, group_id: params[:group_id])
  end

  def move_to_show
    group = Group.find(params[:group_id])
    if group.user != current_user
      redirect_to group_path(params[:group_id])
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :move_to_login_page
  before_action :move_to_show, only: [:edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def new
    @tag_group = TagGroup.new
  end

  def create
    @tag_group = TagGroup.new(tag_group_params)
    if @tag_group.valid?
      @tag_group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @group.comments
    @comment = Comment.new
    @user_group_relation = UserGroupRelation.find_by(user_id: current_user.id, group_id: params[:id])
  end

  def edit
  end

  def update
    @group.update(group_params)
    render :show
  end

  def destroy
    @group.destroy
    redirect_to root_path
  end

  private

  def tag_group_params
    params.require(:tag_group).permit(:title, :details, :start_date, :end_date, :deadline_date, :max_num_of_people, tag_ids: []).merge(user_id: current_user.id)
  end

  def group_params
    params.require(:group).permit(:title, :details, :start_date, :end_date, :deadline_date, :max_num_of_people).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def move_to_show
    if @group.user != current_user
      redirect_to group_path(@group.id)
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :move_to_login_page

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.valid?
      @tag.save
      redirect_to tags_path
    else
      render :new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/user_group_relations_controller.rb
class UserGroupRelationsController < ApplicationController
  before_action :move_to_login_page

  def create
    user_group_relations = UserGroupRelation.new(user_id: current_user.id, group_id: params[:group_id])
    if user_group_relations.valid?
      user_group_relations.save
      redirect_to group_path(params[:group_id])
    else
      redirect_to group_path(params[:group_id])
    end
  end

  def destroy
    user_group_relations = UserGroupRelation.find_by(user_id: current_user.id, group_id: params[:group_id])
    if user_group_relations
      user_group_relations.destroy
    end
    redirect_to group_path(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :move_to_login_page
  before_action :move_to_show, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:nickname)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_show
    if @user != current_user
      redirect_to user_path(@user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_group_relations_helper.rb
module UserGroupRelationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<%= render "shared/header" %>
<h2>this is groups#new</h2>
<%= form_with model: @group, local: true do |f| %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :details, "詳細" %><br />
    <%= f.text_area :details %>
  </div>

  <div class="field">
    <%= f.label :start_date, "開始日時" %><br />
    <%= f.datetime_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date, "終了日時" %><br />
    <%= f.datetime_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :deadline_date, "参加期限" %><br />
    <%= f.datetime_field :deadline_date %>
  </div>

  <div class="field">
    <%= f.label :max_num_of_people, "上限人数" %><br />
    <%= f.number_field :max_num_of_people %>
  </div>

  <div class="field">
    <%= f.label :tag_ids, "タグ選択" %><br />
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>

  <%= f.submit "編集" %>

<% end %>
<%= link_to "戻る", group_path(@group.id) %>
<%= render "shared/footer" %>

app/views/groups/index.html.erb
<%= render "shared/header" %>
<h2>this is groups#index</h2>
<%= link_to "グループ作成", new_group_path %>
<%= link_to "タグ一覧", tags_path %>
<% @groups.each do |group| %><br>
<div style="border: 1px solid black;">
タイトル：<%= link_to group.title, group_path(group.id) %><br>
作成者：<%= link_to group.user.nickname, user_path(group.user.id) %><br>
現在の参加人数：<%= group.user_group_relations.count %>人<br>
</div>
<% end %>
<%= render "shared/footer" %>

app/views/groups/new.html.erb
<%= render "shared/header" %>
<h2>this is groups#new</h2>
<%= form_with model: @tag_group, url: groups_path, local: true do |f| %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :details, "詳細" %><br />
    <%= f.text_area :details %>
  </div>

  <div class="field">
    <%= f.label :start_date, "開始日時" %><br />
    <%= f.datetime_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date, "終了日時" %><br />
    <%= f.datetime_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :deadline_date, "参加期限" %><br />
    <%= f.datetime_field :deadline_date %>
  </div>

  <div class="field">
    <%= f.label :max_num_of_people, "上限人数" %><br />
    <%= f.number_field :max_num_of_people %>
  </div>

  <div class="field">
    <%= f.label :tag_ids, "タグ選択" %><br />
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>

  <%= f.submit "作成" %>

<% end %>

<%= link_to "戻る", root_path %>
<%= render "shared/footer" %>

app/views/groups/show.html.erb
<%= render "shared/header" %>
<h2>this is groups#show</h2>
<div style="border: 1px solid black;">
タイトル：<%= @group.title %><br>
開始時刻：<%= @group.start_date %><br>
終了時刻：<%= @group.end_date %><br>
参加締め切り：<%= @group.deadline_date %><br>
参加上限人数：<%= @group.max_num_of_people %>人<br>
詳細：<%= @group.details %><br>
参加者一覧<br>
<% @group.users.each do |user| %>
<%= user.nickname %><br>
<% end %>

<% if @group.user != current_user %>
  <% if @user_group_relation %>
  <%= link_to "辞退", group_user_group_relation_path(@group.id), method: :delete %><br>
  <% else %>
  <%= link_to "参加", group_user_group_relations_path(@group.id), method: :post %><br>
  <% end %>
<% else %>
<%= link_to "削除", group_path(@group.id), method: :delete %>
<% end %>

</div>
<%= form_with model: @comment, url: group_comments_path(@group.id), method: :post, local: true do |f| %>
<div class="field">
<%= f.text_area :content %>
<%= f.submit "送信" %>
</div>
<% end %>

<% @comments.each do |comment| %>
<div style="border: 1px solid black">
<%= comment.user.nickname %><br>
<%= comment.content %>:<%= link_to "削除", group_comment_path(@group.id, comment.id), method: :delete %><br>
</div>
<% end %>

<%= link_to "グループ編集", edit_group_path(@group.id) %>
<%= link_to "トップへ", root_path %>
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tsunorun34876</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset-context/cssreset-context-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">this is footer</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-left">
  </div>
  <div class="header-right">
  <% if user_signed_in? %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <%= link_to current_user.nickname, user_path(current_user.id) %>
  <% else %>
    <%= link_to "新規登録", new_user_registration_path %>
    <%= link_to "ログイン", new_user_session_path %>
  <% end %>
  </div>
</div>

app/views/shared/_header2.html.erb
<div class="header">
  <div class="header-left">
  </div>
</div>

app/views/tags/index.html.erb
<%= render "shared/header" %>
<h2>this is tags#index</h2>
<% @tags.each do |item| %>
<div style="border: 1px solid black;">
<%= item.name %><br>
<%= link_to "削除", tag_path(item.id), method: :delete %>
</div>
<% end %>
<%= link_to "タグ作成", new_tag_path %>
<%= link_to "戻る", root_path %>
<%= render "shared/footer" %>

app/views/tags/new.html.erb
<%= render "shared/header" %>
<h2>this is tags#new</h2>
<%= form_with model: @tag, local: true do |f| %>

  <div class="field">
    <%= f.label :name, "名前" %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.submit "作成" %>

<% end %>

<%= link_to "戻る", tags_path %>
<%= render "shared/footer" %>

app/views/users/edit.html.erb
<h2>編集</h2>

<h2>this is users#edit</h2>

<%= form_with model: @user, local: true do |f| %>

  <div class="field">
    <%= f.label :nickname, "ニックネーム" %><br />
    <%= f.text_field :nickname, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "保存" %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render "shared/header" %>

<h2>this is users#index</h2>

<% @users.each do |user| %>
<%= link_to user.nickname, user_path(user.id) %><br>
<% end %>
<%= link_to "トップへ", root_path %>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<h2>this is users#show</h2>
名前：<%= @user.nickname %><br>
<% if @user == current_user %>
<%= link_to "編集する", edit_user_path(@user.id) %>
<% end %>
<%= link_to "ユーザー一覧", users_path %>
<%= link_to "トップへ", root_path %>
<%= render "shared/footer" %>